version: "3.8"
services:
  app:
    build: .
    profiles: [production]
    restart: always
    depends_on: [db, redis]
    environment:
      - SERVICE_FQDN_APP_5000

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root-password}
      MYSQL_DATABASE: ${DB_NAME:-main}
      MYSQL_USER: ${DB_USER:-admin}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    volumes: [mysql-data:/var/lib/mysql]

  redis:
    image: redis:latest
    restart: always
    volumes: [redis-data:/data]

volumes:
  mysql-data:
  redis-data:
