version: '3'
services:
    app:
        build: .
        ports:
            - '5000:5000'
        depends_on:
            - db

    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root-password
            MYSQL_DATABASE: main
            MYSQL_USER: admin
            MYSQL_PASSWORD: password
        ports:
            - '3306:3306'
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
