# https://github.com/node-config/node-config/wiki/Environment-Variables

port: PORT
externalUrl: EXTERNAL_URL

jwt:
  secret: JWT_SECRET

database:
  host: DB_HOST
  port: DB_PORT
  database: DB_BASE
  user: DB_USER
  password: DB_PASSWORD

redis:
  host: REDIS_HOST
  port: REDIS_PORT
  user: REDIS_USER
  password: REDIS_PASSWORD
