# for production docker

# sensitive data like secrets and credentials
# should be set as environment variables
# or local.yml file

expose: true

database:
  host: db
  database: main

redis:
  host: redis
